//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Author
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Author()
    {
        this.Books = new HashSet<Book>();
    }

    public long Id { get; set; }
    public string Address { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Book
{
    public long Id { get; set; }
    public Nullable<long> Author_Id { get; set; }
    public string Title { get; set; }

    public virtual Author Author { get; set; }
}

public partial class Student
{
    public long Id { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public string Address { get; set; }
    public string MobileNumber { get; set; }
    public string EmailId { get; set; }
    public string DOB { get; set; }
    public Nullable<long> ClassId { get; set; }
    public Nullable<long> SectionId { get; set; }
    public string Description { get; set; }
    public string ProfilePicture { get; set; }
    public Nullable<bool> IsDisabled { get; set; }
}

public partial class TSC
{
    public long Id { get; set; }
    public Nullable<long> TeacherId { get; set; }
    public Nullable<long> SubjectId { get; set; }
    public Nullable<long> Class { get; set; }
    public Nullable<long> Section { get; set; }
    public Nullable<bool> IsDisabled { get; set; }
}
